name: Deploy nodeppt-set

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    strategy:
      matrix:
        node-version: [14.x]

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 下载代码仓库

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.) 缓存压缩 node_modules，不用每次下载，使用时解压，可以加快工作流的执行过程，超过 7 天没有使用将删除压缩包。
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
        run: npm install # 安装 node modules 相关依赖

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy

      - name: Deploy to Server # rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='node_modules/*' # rsync参数，排除node_modules
          SERVER_PORT: ${{ secrets.SSH_HOST_PORT }} # SSH端口
          FOLDER: ./build # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /home/${{ secrets.SSH_USERNAME }}/www/ppt # 部署到目标文件夹
      # - name: Restart server # 第三步，重启服务
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.DEPLOY_KEY }}
      #     # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
      #     script: |
      #       cd /home/fming/mysite/
      #       python manage.py migrate
      #       supervisorctl restart web
